workflows:
  android-development:
    name: Android Development Build
    environment:
      groups:
        - android_config
      vars:
        BUILD_TOOLS: "34.0.0"
    scripts:
      - name: Build Android APK
        script: |
          chmod +x ./gradlew
          ls -la ./gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
