workflows:
  android-game-translator:
    name: Game Translator Build
    environment:
      android_signing: null
    scripts:
      - name: Build with Gradle
        script: |
          # Используем системный Gradle вместо gradlew
          gradle clean assembleDebug bundleRelease --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/bundle/release/app-release.aab
