workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Build Release APK
        script: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
