workflows:
  android-debug:
    name: Android Build
    scripts:
      - name: Build with system Gradle
        script: |
          # Просто используем системный Gradle
          gradle assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
