workflows:
  android-build:
    name: Android Game Translator Build
    scripts:
      - name: Build APK and AAB
        script: |
          ./gradlew clean assembleDebug bundleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
