workflows:
  android-game-translator:  # Это правильное имя workflow
    name: Android Game Translator
    environment:
      groups: []
    scripts:
      - name: Set execute permission for gradlew
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew clean assembleDebug
      - name: Build Release AAB
        script: ./gradlew clean bundleRelease
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
