workflows:
  android-development:
    name: Android Development Build
    environment:
      android:
        build_tools: "34.0.0"
    scripts:
      - name: Build Android APK
        script: |
          chmod +x ./gradlew
          ls -la ./gradlew  # Проверим права
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
